name: Podcast generator
author: "Arslan Yousaf"
description: "Generate podcast from YAML feed"
runs:
    using: "docker"
    image: "Dockerfile"
branding:
    color: "red"
    icon: "git-branch"
inputs:
    email:
        description: "Commiter's Email address"
        required: true
        default: ${{ github.actor }}@users.noreply.github.com
    name:
        description: "Commiter's Name"
        required: true
        default: ${{ github.actor }}
